#!/bin/bash
python3 -m venv /usr/lib/certnotify/venv
source /usr/lib/certnotify/venv/bin/activate
pip install --upgrade pip
pip install cryptography
if [ ! -f /root/.config/certnotify.conf ]; then
  python3 "/usr/lib/certnotify/certnotify.py" --reset
fi
exit